name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Install dependencies
      run: |
        cd frontend
        pnpm install --no-frozen-lockfile
      
    - name: Build frontend
      run: |
        cd frontend
        pnpm run build
      env:
        # 设置环境变量用于构建
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL || 'https://dhfmucngbriiocvjhgwf.supabase.co' }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_AMAP_KEY: ${{ secrets.VITE_AMAP_KEY }}
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL || 'http://localhost:8080' }}
        VITE_JOYAGENT_API_URL: ${{ secrets.VITE_JOYAGENT_API_URL || 'http://localhost:8080' }}
        VITE_APP_ENV: production
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./frontend/dist

  # GitHub Pages 部署
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

